### ISSUE TITLE
php unit test fails in nightly

### ISSUE THREAD

**Issue by Talank** [owncloud/files_primary_s3#569]
https://drone.owncloud.com/owncloud/files_primary_s3/2948/4/8

```
+ make test-php-unit-dbg
cd ../../tests && phpdbg -qrr -d memory_limit=12G -d zend.enable_gc=0 "/var/www/owncloud/server/apps/files_primary_s3/../../lib/composer/bin/phpunit" --configuration ./phpunit-autotest.xml --coverage-clover ../apps/files_primary_s3/tests/output/clover.xml
[Uncaught PHPUnit\TextUI\RuntimeException in /var/www/owncloud/server/lib/composer/phpunit/phpunit/src/TextUI/Command.php on line 98]
Error: Class 'OCA\Notifications\Tests\Unit\TestCase' not found in /var/www/owncloud/server/apps/notifications/tests/unit/AppInfo/AppTest.php:34
Stack trace:
#0 /var/www/owncloud/server/tests/apps.php(23): require_once()
#1 /var/www/owncloud/server/tests/apps.php(21): loadDirectory()
#2 /var/www/owncloud/server/tests/apps.php(21): loadDirectory()
#3 /var/www/owncloud/server/tests/apps.php(54): loadDirectory()
#4 /var/www/owncloud/server/lib/composer/phpunit/phpunit/src/Util/FileLoader.php(65): include_once('/var/www/ownclo...')
#5 /var/www/owncloud/server/lib/composer/phpunit/phpunit/src/Util/FileLoader.php(49): PHPUnit\Util\FileLoader::load()
#6 /var/www/owncloud/server/lib/composer/phpunit/phpunit/src/Framework/TestSuite.php(401): PHPUnit\Util\FileLoader::checkAndLoad()
#7 /var/www/owncloud/server/lib/composer/phpunit/phpunit/src/TextUI/TestSuiteMapper.php(84): PHPUnit\Framework\TestSuite->addTestFile()
#8 /var/www/owncloud/server/lib/composer/phpunit/phpunit/src/TextUI/Command.php(390): PHPUnit\TextUI\TestSuiteMapper->map()
#9 /var/www/owncloud/server/lib/composer/phpunit/phpunit/src/TextUI/Command.php(111): PHPUnit\TextUI\Command->handleArguments()
#10 /var/www/owncloud/server/lib/composer/phpunit/phpunit/src/TextUI/Command.php(96): PHPUnit\TextUI\Command->run()
#11 /var/www/owncloud/server/lib/composer/phpunit/phpunit/phpunit(98): PHPUnit\TextUI\Command::main()
#12 {main}

Next PHPUnit\TextUI\RuntimeException: Class 'OCA\Notifications\Tests\Unit\TestCase' not found in /var/www/owncloud/server/lib/composer/phpunit/phpunit/src/TextUI/Command.php:98
Stack trace:
#0 /var/www/owncloud/server/lib/composer/phpunit/phpunit/phpunit(98): PHPUnit\TextUI\Command::main()
#1 {main}
make: *** [test-php-unit-dbg] Error 255
Makefile:98: recipe for target 'test-php-unit-dbg' failed
```

failing since last few days in nightly.

**Comment by SagarGi** [comment]
unit tests not failing after this PR https://github.com/owncloud/files_primary_s3/pull/570 so, closing this issue.
