### ISSUE TITLE
`files_primary_s3` is incompatible with `files_external_s3` and breaks installations where both are installed

### ISSUE THREAD

**Issue by posita** [owncloud/files_primary_s3#627]
Summary: `files_primary_s3` cannot be installed alongside `files_external_s3`, even if no user mounts external storage. Just having both apps results in `Call to undefined function Aws\boolean_value()` errors due to mutually incompatible versions of the AWS SDK being installed with each app.

I have been recently inundated with errors in `owncloud.log` like the following:

``` javascript
{
  "reqId": "[redacted]",
  "level": 4,
  "time": "2022-11-13T23:28:34+00:00",
  "remoteAddr": "73.177.1.136",
  "user": "admin",
  "app": "webdav",
  "method": "GET",
  "url": "/remote.php/webdav/ownCloud%20Manual.pdf",
  "message": "Exception: Call to undefined function Aws\\boolean_value(): {\"Exception\":\"Error\",\"Message\":\"Call to undefined function Aws\\\\boolean_value()\",\"Code\":0,\"Trace\":\"#0 [redacted]apps-external\\/files_primary_s3\\/vendor\\/aws\\/aws-sdk-php\\/src\\/Endpoint\\/UseFipsEndpoint\\/ConfigurationProvider.php(174): Aws\\\\Endpoint\\\\UseFipsEndpoint\\\\Configuration->__construct(false)\\n#1 [redacted]apps-external\\/files_primary_s3\\/vendor\\/guzzlehttp\\/promises\\/src\\/Promise.php(204): Aws\\\\Endpoint\\\\UseFipsEndpoint\\\\ConfigurationProvider::Aws\\\\Endpoint\\\\UseFipsEndpoint\\\\{closure}(*** sensitive parameters replaced ***)\\n#2 [redacted]apps-external\\/files_primary_s3\\/vendor\\/guzzlehttp\\/promises\\/src\\/Promise.php(169): GuzzleHttp\\\\Promise\\\\Promise::callHandler(2, Object(Aws\\\\Endpoint\\\\UseFipsEndpoint\\\\Exception\\\\ConfigurationException), NULL)\\n#3 [redacted]apps-external\\/files_primary_s3\\/vendor\\/guzzlehttp\\/promises\\/src\\/RejectedPromise.php(42): GuzzleHttp\\\\Promise\\\\Promise::GuzzleHttp\\\\Promise\\\\{closure}(*** sensitive parameters replaced ***)\\n#4 [redacted]apps-external\\/files_primary_s3\\/vendor\\/guzzlehttp\\/promises\\/src\\/TaskQueue.php(48): GuzzleHttp\\\\Promise\\\\RejectedPromise::GuzzleHttp\\\\Promise\\\\{closure}(*** sensitive parameters replaced ***)\\n#5 [redacted]apps-external\\/files_primary_s3\\/vendor\\/guzzlehttp\\/promises\\/src\\/Promise.php(248): GuzzleHttp\\\\Promise\\\\TaskQueue->run(true)\\n#6 [redacted]apps-external\\/files_primary_s3\\/vendor\\/guzzlehttp\\/promises\\/src\\/Promise.php(224): GuzzleHttp\\\\Promise\\\\Promise->invokeWaitFn()\\n#7 [redacted]apps-external\\/files_primary_s3\\/vendor\\/guzzlehttp\\/promises\\/src\\/Promise.php(269): GuzzleHttp\\\\Promise\\\\Promise->waitIfPending()\\n#8 [redacted]apps-external\\/files_primary_s3\\/vendor\\/guzzlehttp\\/promises\\/src\\/Promise.php(226): GuzzleHttp\\\\Promise\\\\Promise->invokeWaitList()\\n#9 [redacted]apps-external\\/files_primary_s3\\/vendor\\/guzzlehttp\\/promises\\/src\\/Promise.php(62): GuzzleHttp\\\\Promise\\\\Promise->waitIfPending()\\n#10 [redacted]apps-external\\/files_primary_s3\\/vendor\\/aws\\/aws-sdk-php\\/src\\/ClientResolver.php(677): GuzzleHttp\\\\Promise\\\\Promise->wait()\\n#11 [redacted]apps-external\\/files_primary_s3\\/vendor\\/aws\\/aws-sdk-php\\/src\\/ClientResolver.php(352): Aws\\\\ClientResolver::_apply_use_fips_endpoint(Object(GuzzleHttp\\\\Promise\\\\Promise), Array, Object(Aws\\\\HandlerList))\\n#12 [redacted]apps-external\\/files_primary_s3\\/vendor\\/aws\\/aws-sdk-php\\/src\\/AwsClient.php(199): Aws\\\\ClientResolver->resolve(Array, Object(Aws\\\\HandlerList))\\n#13 [redacted]apps-external\\/files_primary_s3\\/vendor\\/aws\\/aws-sdk-php\\/src\\/S3\\/S3Client.php(355): Aws\\\\AwsClient->__construct(Array)\\n#14 [redacted]apps-external\\/files_primary_s3\\/vendor\\/aws\\/aws-sdk-php\\/src\\/AwsClient.php(462): Aws\\\\S3\\\\S3Client->__construct(Array)\\n#15 [redacted]apps-external\\/files_primary_s3\\/lib\\/s3storage.php(103): Aws\\\\AwsClient::factory(Array)\\n#16 [redacted]apps-external\\/files_primary_s3\\/lib\\/s3storage.php(262): OCA\\\\Files_Primary_S3\\\\S3Storage->init()\\n#17 [redacted]lib\\/private\\/Files\\/ObjectStore\\/ObjectStoreStorage.php(313): OCA\\\\Files_Primary_S3\\\\S3Storage->readObject('urn:oid:20')\\n#18 [redacted]lib\\/private\\/Files\\/Storage\\/Wrapper\\/Wrapper.php(303): OC\\\\Files\\\\ObjectStore\\\\ObjectStoreStorage->fopen('files\\/ownCloud ...', 'r')\\n#19 [redacted]lib\\/private\\/Files\\/Storage\\/Wrapper\\/Availability.php(317): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->fopen('files\\/ownCloud ...', 'r')\\n#20 [redacted]lib\\/private\\/Files\\/Storage\\/Wrapper\\/Encryption.php(931): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->fopen('files\\/ownCloud ...', 'r')\\n#21 [redacted]lib\\/private\\/Files\\/Storage\\/Wrapper\\/Encryption.php(1006): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->readFirstBlock('files\\/ownCloud ...')\\n#22 [redacted]lib\\/private\\/Files\\/Storage\\/Wrapper\\/Encryption.php(381): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->getHeader('files\\/ownCloud ...')\\n#23 [redacted]lib\\/private\\/Files\\/Storage\\/Wrapper\\/Checksum.php(59): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->fopen('files\\/ownCloud ...', 'rb')\\n#24 [redacted]lib\\/private\\/Files\\/Storage\\/Wrapper\\/Wrapper.php(303): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Checksum->fopen('files\\/ownCloud ...', 'rb')\\n#25 [redacted]lib\\/private\\/Files\\/View.php(1224): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->fopen('files\\/ownCloud ...', 'rb')\\n#26 [redacted]lib\\/private\\/Files\\/View.php(1070): OC\\\\Files\\\\View->basicOperation('fopen', '\\/ownCloud Manua...', Array, 'rb')\\n#27 [redacted]apps\\/dav\\/lib\\/Connector\\/Sabre\\/File.php(431): OC\\\\Files\\\\View->fopen('ownCloud Manual...', 'rb')\\n#28 [redacted]lib\\/composer\\/sabre\\/dav\\/lib\\/DAV\\/CorePlugin.php(85): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->get()\\n#29 [redacted]lib\\/composer\\/sabre\\/event\\/lib\\/WildcardEmitterTrait.php(89): Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#30 [redacted]lib\\/composer\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(472): Sabre\\\\DAV\\\\Server->emit('method:GET', Array)\\n#31 [redacted]lib\\/composer\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(253): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#32 [redacted]lib\\/composer\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(321): Sabre\\\\DAV\\\\Server->start()\\n#33 [redacted]apps\\/dav\\/appinfo\\/v1\\/webdav.php(67): Sabre\\\\DAV\\\\Server->exec()\\n#34 [redacted]remote.php(165): require_once('[redacted]...')\\n#35 {main}\",\"File\":\"[redacted]apps-external\\/files_primary_s3\\/vendor\\/aws\\/aws-sdk-php\\/src\\/Endpoint\\/UseFipsEndpoint\\/Configuration.php\",\"Line\":14}"
}

```

My configuration:

``` php
<?php
$CONFIG = array (
  // ...
  'objectstore' =>
  array (
    'class' => 'OCA\\Files_Primary_S3\\S3Storage',
    'arguments' =>
    array (
      'bucket' => '[redacted]',
      'options' =>
      array (
        'version' => '2006-03-01',  // also tried 'latest` with no effect
        'use_arn_region' => false,
        'region' => 'us-east-1',
        'credentials' =>
        array (
          'key' => '[redacted]',
          'secret' => '[redacted]',
        ),
        'endpoint' => 'https://s3.us-east-1.wasabisys.com/',
        'use_path_style_endpoint' => true,
      ),
    ),
  ),
  // ...
}
```

### Environment general
**Operating system**: Linux

``` sh
% uname -srvmpio
Linux 4.14.117-grsec-grsec+ owncloud/web#1 SMP Fri May 10 17:15:47 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Backend (ownCloud Core or Infinite Scale)**: core

**Are you using an external user-backend, if yes which one:** none

### Environment ownCloud Core
**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.4.15

**Version:** 10.11.0.6

**Updated from an older ownCloud or fresh install:** updated

**Where did you install ownCloud from:** tarball

**Signing status (ownCloud 9.0 and above):** ???

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results into https://gist.github.com/ and put the link here.
```

https://gist.github.com/posita/e6ccab936c7b99ff8463221b47153a20#file-failed

**The content of config/config.php:**

https://gist.github.com/posita/e6ccab936c7b99ff8463221b47153a20#file-occ-config-list-system

**List of activated apps:**

https://gist.github.com/posita/e6ccab936c7b99ff8463221b47153a20#file-occ-app-list

**Are you using external storage, if yes which one:** s3

**Are you using encryption:**  no (not available with s3)

**Comment by posita** [comment]
FWIW, that interior stack trace is as follows:

```
#0 [redacted]apps-external/files_primary_s3/vendor/aws/aws-sdk-php/src/Endpoint/UseFipsEndpoint/ConfigurationProvider.php(174): Aws\Endpoint\UseFipsEndpoint\Configuration->__construct(false)
#1 [redacted]apps-external/files_primary_s3/vendor/guzzlehttp/promises/src/Promise.php(204): Aws\Endpoint\UseFipsEndpoint\ConfigurationProvider::Aws\Endpoint\UseFipsEndpoint\{closure}(*** sensitive parameters replaced ***)
#2 [redacted]apps-external/files_primary_s3/vendor/guzzlehttp/promises/src/Promise.php(169): GuzzleHttp\Promise\Promise::callHandler(2, Object(Aws\Endpoint\UseFipsEndpoint\Exception\ConfigurationException), NULL)
#3 [redacted]apps-external/files_primary_s3/vendor/guzzlehttp/promises/src/RejectedPromise.php(42): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}(*** sensitive parameters replaced ***)
#4 [redacted]apps-external/files_primary_s3/vendor/guzzlehttp/promises/src/TaskQueue.php(48): GuzzleHttp\Promise\RejectedPromise::GuzzleHttp\Promise\{closure}(*** sensitive parameters replaced ***)
#5 [redacted]apps-external/files_primary_s3/vendor/guzzlehttp/promises/src/Promise.php(248): GuzzleHttp\Promise\TaskQueue->run(true)
#6 [redacted]apps-external/files_primary_s3/vendor/guzzlehttp/promises/src/Promise.php(224): GuzzleHttp\Promise\Promise->invokeWaitFn()
#7 [redacted]apps-external/files_primary_s3/vendor/guzzlehttp/promises/src/Promise.php(269): GuzzleHttp\Promise\Promise->waitIfPending()
#8 [redacted]apps-external/files_primary_s3/vendor/guzzlehttp/promises/src/Promise.php(226): GuzzleHttp\Promise\Promise->invokeWaitList()
#9 [redacted]apps-external/files_primary_s3/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\Promise\Promise->waitIfPending()
#10 [redacted]apps-external/files_primary_s3/vendor/aws/aws-sdk-php/src/ClientResolver.php(677): GuzzleHttp\Promise\Promise->wait()
#11 [redacted]apps-external/files_primary_s3/vendor/aws/aws-sdk-php/src/ClientResolver.php(352): Aws\ClientResolver::_apply_use_fips_endpoint(Object(GuzzleHttp\Promise\Promise), Array, Object(Aws\HandlerList))
#12 [redacted]apps-external/files_primary_s3/vendor/aws/aws-sdk-php/src/AwsClient.php(199): Aws\ClientResolver->resolve(Array, Object(Aws\HandlerList))
#13 [redacted]apps-external/files_primary_s3/vendor/aws/aws-sdk-php/src/S3/S3Client.php(355): Aws\AwsClient->__construct(Array)
#14 [redacted]apps-external/files_primary_s3/vendor/aws/aws-sdk-php/src/AwsClient.php(462): Aws\S3\S3Client->__construct(Array)
#15 [redacted]apps-external/files_primary_s3/lib/s3storage.php(103): Aws\AwsClient::factory(Array)
#16 [redacted]apps-external/files_primary_s3/lib/s3storage.php(262): OCA\Files_Primary_S3\S3Storage->init()
#17 [redacted]lib/private/Files/ObjectStore/ObjectStoreStorage.php(313): OCA\Files_Primary_S3\S3Storage->readObject('urn:oid:20')
#18 [redacted]lib/private/Files/Storage/Wrapper/Wrapper.php(303): OC\Files\ObjectStore\ObjectStoreStorage->fopen('files/ownCloud ...', 'r')
#19 [redacted]lib/private/Files/Storage/Wrapper/Availability.php(317): OC\Files\Storage\Wrapper\Wrapper->fopen('files/ownCloud ...', 'r')
#20 [redacted]lib/private/Files/Storage/Wrapper/Encryption.php(931): OC\Files\Storage\Wrapper\Availability->fopen('files/ownCloud ...', 'r')
#21 [redacted]lib/private/Files/Storage/Wrapper/Encryption.php(1006): OC\Files\Storage\Wrapper\Encryption->readFirstBlock('files/ownCloud ...')
#22 [redacted]lib/private/Files/Storage/Wrapper/Encryption.php(381): OC\Files\Storage\Wrapper\Encryption->getHeader('files/ownCloud ...')
#23 [redacted]lib/private/Files/Storage/Wrapper/Checksum.php(59): OC\Files\Storage\Wrapper\Encryption->fopen('files/ownCloud ...', 'rb')
#24 [redacted]lib/private/Files/Storage/Wrapper/Wrapper.php(303): OC\Files\Storage\Wrapper\Checksum->fopen('files/ownCloud ...', 'rb')
#25 [redacted]lib/private/Files/View.php(1224): OC\Files\Storage\Wrapper\Wrapper->fopen('files/ownCloud ...', 'rb')
#26 [redacted]lib/private/Files/View.php(1070): OC\Files\View->basicOperation('fopen', '/ownCloud Manua...', Array, 'rb')
#27 [redacted]apps/dav/lib/Connector/Sabre/File.php(431): OC\Files\View->fopen('ownCloud Manual...', 'rb')
#28 [redacted]lib/composer/sabre/dav/lib/DAV/CorePlugin.php(85): OCA\DAV\Connector\Sabre\File->get()
#29 [redacted]lib/composer/sabre/event/lib/WildcardEmitterTrait.php(89): Sabre\DAV\CorePlugin->httpGet(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#30 [redacted]lib/composer/sabre/dav/lib/DAV/Server.php(472): Sabre\DAV\Server->emit('method:GET', Array)
#31 [redacted]lib/composer/sabre/dav/lib/DAV/Server.php(253): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
#32 [redacted]lib/composer/sabre/dav/lib/DAV/Server.php(321): Sabre\DAV\Server->start()
#33 [redacted]apps/dav/appinfo/v1/webdav.php(67): Sabre\DAV\Server->exec()
#34 [redacted]remote.php(165): require_once('[redacted]...')
#35 {main}
```

**Comment by posita** [comment]
This seems to fail no matter which S3 provider I use. (I've tried Wasabi and DreamObjects, both of which were working as recently as several weeks ago.)

**Comment by posita** [comment]
Okay, I think I figured this out. I had _also_ installed and enabled `files_external_s3` so users could add their own storage. `occ app:disable files_external_s3` cleared up these errors. So it appears they are not compatible with each other, even though one can install them side-by-side and configure them without apparent issue.

**Comment by enbrnz** [comment]
I just saw this now, but I just had a test instance with files_primary_s3 active and working as well as an admin and a user files_external_s3 mount. And was working fine for me, however I have already deleted the backend configurations already.

**Comment by posita** [comment]
@enbrnz, what versions where you using?

**Comment by enbrnz** [comment]
`ownCloud` `10.11` & `files_primary_s3` `1.4.0` & `files_external_s3` `2.1.0`
I was using a self hosted minio S3 backend for `files_primary_s3`.
And Google Cloud Storage as external S3 mount.

**Comment by posita** [comment]
With the above versions, I can confirm that the two apps can now be installed and enabled side-by-side. I'm curious, though: What prevents AWS SDK version skew/incompatibility between apps in the future?

See, e.g. owncloud/files_primary_s3#655 vs owncloud/files_external_s3#1053.

Forgive me for not being familiar enough with PHP, but does it have some kind of namespace isolation mechanism to allow each app to use its own (expected) version of third party packages without interfering with each other?

**Comment by enbrnz** [comment]
I am sorry, but I have no clue myself. There was recently an upgrade of Guzzle versions, this could have something to do with it, but doesn't have to...
