### ISSUE TITLE
Files_Primary_S3 unable to read from stream files >10MB

### ISSUE THREAD

**Issue by Fen0l** [owncloud/files_primary_s3#638]
I am experiencing lots of random issues with the Files-primary-s3 storage since few days. Currently running the latest version with OC 10.11.

I am using an external S3 Storage (MiniO) but we are getting a lots of "Unable to read from stream" during uploads/downloads. It is working perfectly for small files <10MB.

As for now, we are getting the Unable to read from stream every time we upload/download large files

```
{
	"reqId":"e3a1fec46395af1675d92d6f3c70e0bc",
	"level":4,
	"time":"2022-12-19T09:31:37+00:00",
	"remoteAddr":"172.18.160.248",
	"user":"TESTING_USERS",
	"app":"webdav",
	"method":"MOVE",
	"url":"/remote.php/dav/uploads/TESTING_USERS/web-file-upload-71c421fe3ac400a826b2f6083a221fd6-1671442234988/.file",
	"message":"Exception: HTTP/1.1 500 Unable to read from stream: {"Exception":"Sabre\DAV\Exception","Message":"Unable to read from stream","Code":0,"Trace":"
#0 /var/www/owncloud/apps/dav/lib/Connector/Sabre/File.php(240): OCA\DAV\Connector\Sabre\File->convertToSabreException()
#1 /var/www/owncloud/apps/dav/lib/Connector/Sabre/Directory.php(173): OCA\DAV\Connector\Sabre\File->put()
#2 /var/www/owncloud/lib/composer/sabre/dav/lib/DAV/Tree.php(307): OCA\DAV\Connector\Sabre\Directory->createFile()
#3 /var/www/owncloud/lib/composer/sabre/dav/lib/DAV/Tree.php(133): Sabre\DAV\Tree->copyNode()
#4 /var/www/owncloud/apps/dav/lib/Tree.php(113): Sabre\DAV\Tree->copy()
#5 /var/www/owncloud/lib/composer/sabre/dav/lib/DAV/Tree.php(163): OCA\DAV\Tree->copy()
#6 /var/www/owncloud/lib/composer/sabre/dav/lib/DAV/CorePlugin.php(612): Sabre\DAV\Tree->move()
#7 /var/www/owncloud/lib/composer/sabre/event/lib/WildcardEmitterTrait.php(89): Sabre\DAV\CorePlugin->httpMove()
#8 /var/www/owncloud/lib/composer/sabre/dav/lib/DAV/Server.php(472): Sabre\DAV\Server->emit()
#9 /var/www/owncloud/lib/composer/sabre/dav/lib/DAV/Server.php(253): Sabre\DAV\Server->invokeMethod()
#10 /var/www/owncloud/apps/dav/lib/Server.php(349): Sabre\DAV\Server->start()
#11 /var/www/owncloud/apps/dav/appinfo/v2/remote.php(31): OCA\DAV\Server->exec()
#12 /var/www/owncloud/remote.php(165): require_once('/var/www/ownclo...')
#13 {main}","File":"/var/www/owncloud/apps/dav/lib/Connector/Sabre/File.php","Line":731}"
}

{
	"reqId":"e3a1fec46395af1675d92d6f3c70e0bc",
	"level":4,
	"time":"2022-12-19T09:31:37+00:00",
	"remoteAddr":"172.18.160.248",
	"user":"TESTING_USERS",
	"app":"webdav",
	"method":"MOVE",
	"url":"/remote.php/dav/uploads/TESTING_USERS/web-file-upload-71c421fe3ac400a826b2f6083a221fd6-1671442234988/.file",
	"message":"Caused by: {"Exception":"RuntimeException","Message":"Unable to read from stream","Code":0,"Trace":"
#0 /var/www/owncloud/lib/composer/guzzlehttp/psr7/src/CachingStream.php(102): GuzzleHttp\Psr7\Stream->read()
#1 /var/www/owncloud/apps/files_primary_s3/lib/streamwrapper.php(181): GuzzleHttp\Psr7\CachingStream->read()
#2 [internal function]: OCA\Files_Primary_S3\StreamWrapper->stream_read()
#3 /var/www/owncloud/lib/composer/icewind/streams/src/Wrapper.php(55): fread()
#4 /var/www/owncloud/lib/private/Files/Stream/Checksum.php(112): Icewind\Streams\Wrapper->stream_read()
#5 [internal function]: OC\Files\Stream\Checksum->stream_read()
#6 /var/www/owncloud/lib/composer/icewind/streams/src/Wrapper.php(55): fread()
#7 /var/www/owncloud/lib/composer/icewind/streams/src/CallbackWrapper.php(96): Icewind\Streams\Wrapper->stream_read()
#8 [internal function]: Icewind\Streams\CallbackWrapper->stream_read()
#9 /var/www/owncloud/lib/composer/icewind/streams/src/Wrapper.php(55): fread()
#10 /var/www/owncloud/lib/composer/icewind/streams/src/CallbackWrapper.php(96): Icewind\Streams\Wrapper->stream_read()
#11 [internal function]: Icewind\Streams\CallbackWrapper->stream_read()
#12 /var/www/owncloud/apps/dav/lib/Upload/AssemblyStream.php(126): fread()
#13 [internal function]: OCA\DAV\Upload\AssemblyStream->stream_read()
#14 /var/www/owncloud/lib/private/legacy/helper.php(298): fread()
#15 /var/www/owncloud/apps/dav/lib/Connector/Sabre/File.php(208): OC_Helper::streamCopy()
#16 /var/www/owncloud/apps/dav/lib/Connector/Sabre/Directory.php(173): OCA\DAV\Connector\Sabre\File->put()
#17 /var/www/owncloud/lib/composer/sabre/dav/lib/DAV/Tree.php(307): OCA\DAV\Connector\Sabre\Directory->createFile()
#18 /var/www/owncloud/lib/composer/sabre/dav/lib/DAV/Tree.php(133): Sabre\DAV\Tree->copyNode()
#19 /var/www/owncloud/apps/dav/lib/Tree.php(113): Sabre\DAV\Tree->copy()
#20 /var/www/owncloud/lib/composer/sabre/dav/lib/DAV/Tree.php(163): OCA\DAV\Tree->copy()
#21 /var/www/owncloud/lib/composer/sabre/dav/lib/DAV/CorePlugin.php(612): Sabre\DAV\Tree->move()
#22 /var/www/owncloud/lib/composer/sabre/event/lib/WildcardEmitterTrait.php(89): Sabre\DAV\CorePlugin->httpMove()
#23 /var/www/owncloud/lib/composer/sabre/dav/lib/DAV/Server.php(472): Sabre\DAV\Server->emit()
#24 /var/www/owncloud/lib/composer/sabre/dav/lib/DAV/Server.php(253): Sabre\DAV\Server->invokeMethod()
#25 /var/www/owncloud/apps/dav/lib/Server.php(349): Sabre\DAV\Server->start()
#26 /var/www/owncloud/apps/dav/appinfo/v2/remote.php(31): OCA\DAV\Server->exec()
#27 /var/www/owncloud/remote.php(165): require_once('/var/www/ownclo...')
#28 {main}","File":"/var/www/owncloud/lib/composer/guzzlehttp/psr7/src/Stream.php","Line":237}"
}

```

php limits are higher than 1GB, but it seems to come from the S3 applications. Would anyone here already face this issue ?
```
upload_max_filesize=5G
post_max_size=5G
memory_limit=2G
mbstring.func_overload=0
always_populate_raw_post_data=-1
default_charset='UTF-8'
output_buffering=0
```

HTTP Trace:
```
Request URL: https://ENDPOINT/remote.php/dav/uploads/UESR_TESTINGS/web-file-upload-71c421fe3ac400a826b2f6083a221fd6-1671442641882/.file
Request Method: MOVE
Status Code: 500 Internal Server Error
Remote Address: 194.154.209.148:443
Referrer Policy: no-referrer

<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception</s:exception>
  <s:message>Unable to read from stream</s:message>
</d:error>

```
Here the object configuration settings:

```
declare -x OWNCLOUD_OBJECTSTORE_AUTOCREATE="true"
declare -x OWNCLOUD_OBJECTSTORE_BUCKET="owncloud-uat"
declare -x OWNCLOUD_OBJECTSTORE_CLASS="OCA\Files_Primary_S3\S3Storage"
declare -x OWNCLOUD_OBJECTSTORE_ENABLED="true"
declare -x OWNCLOUD_OBJECTSTORE_ENDPOINT="https://minio.local"
declare -x OWNCLOUD_OBJECTSTORE_KEY="_"
declare -x OWNCLOUD_OBJECTSTORE_PATHSTYLE="true"
declare -x OWNCLOUD_OBJECTSTORE_REGION="us-east-1"
declare -x OWNCLOUD_OBJECTSTORE_SECRET=""
declare -x OWNCLOUD_OBJECTSTORE_VERSION="2006-03-01"

with
'concurrency' => 5
'part_size' => 5242880
```

I tested the object storage and I am able to upload/download larger files. But failing from owncloud
Many thanks in advance for your inputs,

**Comment by DeepDiver1975** [comment]
please retest this app with version 1.5.0 THX
