### ISSUE TITLE
Error on first logging if folder was shared beforehand

### ISSUE THREAD

**Issue by patrickjahns** [owncloud/files_primary_s3#73]
When a user first logins, if he already has a folder shared, he will receive an "internal server error" screen. 
Login attempt on second try works - however - the skeleton files/folder is not copied over

## Steps to reproduce

still reproducing - the error below points to an infrastructure error - or a weird edge case 
(docker environment has inbetween been recreated)

## Log
`owncloud.log` entries
```
{"reqId":"Tv2vUJIZDclZYDiF9HcY","level":3,"time":"2018-05-31T17:45:22+00:00","remoteAddr":"172.18.0.7","user":"dbuser","app":"no app in context","method":"POST","url":"\/login","message":"Exception: {\"Exception\":\"Aws\\\\S3\\\\Exception\\\\S3Exception\",\"Message\":\"Error executing \\\"ListBuckets\\\" on \\\"http:\\\/\\\/ceph\\\/\\\"; AWS HTTP error: Error creating resource: [message] fopen(): php_network_getaddresses: getaddrinfo failed: Name or service not known\\n[file] \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_primary_s3\\\/vendor\\\/guzzlehttp\\\/ringphp\\\/src\\\/Client\\\/StreamHandler.php\\n[line] 406\\n[message] fopen(http:\\\/\\\/ceph\\\/): failed to open stream: php_network_getaddresses: getaddrinfo failed: Name or service not known\\n[file] \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_primary_s3\\\/vendor\\\/guzzlehttp\\\/ringphp\\\/src\\\/Client\\\/StreamHandler.php\\n[line] 406\\n[message] Undefined variable: http_response_header\\n[file] \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_primary_s3\\\/vendor\\\/guzzlehttp\\\/ringphp\\\/src\\\/Client\\\/StreamHandler.php\\n[line] 407\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_primary_s3\\\/vendor\\\/aws\\\/aws-sdk-php\\\/src\\\/WrappedHttpHandler.php(100): Aws\\\\WrappedHttpHandler->parseError(Array, Object(GuzzleHttp\\\\Psr7\\\\Request), Object(Aws\\\\Command), Array)\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_primary_s3\\\/vendor\\\/guzzlehttp\\\/promises\\\/src\\\/Promise.php(203): Aws\\\\WrappedHttpHandler->Aws\\\\{closure}(Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_primary_s3\\\/vendor\\\/guzzlehttp\\\/promises\\\/src\\\/Promise.php(174): GuzzleHttp\\\\Promise\\\\Promise::callHandler(2, Array, Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_primary_s3\\\/vendor\\\/guzzlehttp\\\/promises\\\/src\\\/RejectedPromise.php(40): GuzzleHttp\\\\Promise\\\\Promise::GuzzleHttp\\\\Promise\\\\{closure}(Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_primary_s3\\\/vendor\\\/guzzlehttp\\\/promises\\\/src\\\/TaskQueue.php(47): GuzzleHttp\\\\Promise\\\\RejectedPromise::GuzzleHttp\\\\Promise\\\\{closure}()\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_primary_s3\\\/vendor\\\/guzzlehttp\\\/promises\\\/src\\\/Promise.php(246): GuzzleHttp\\\\Promise\\\\TaskQueue->run(true)\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_primary_s3\\\/vendor\\\/guzzlehttp\\\/promises\\\/src\\\/Promise.php(223): GuzzleHttp\\\\Promise\\\\Promise->invokeWaitFn()\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_primary_s3\\\/vendor\\\/guzzlehttp\\\/promises\\\/src\\\/Promise.php(267): GuzzleHttp\\\\Promise\\\\Promise->waitIfPending()\\n#8 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_primary_s3\\\/vendor\\\/guzzlehttp\\\/promises\\\/src\\\/Promise.php(225): GuzzleHttp\\\\Promise\\\\Promise->invokeWaitList()\\n#9 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_primary_s3\\\/vendor\\\/guzzlehttp\\\/promises\\\/src\\\/Promise.php(62): GuzzleHttp\\\\Promise\\\\Promise->waitIfPending()\\n#10 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_primary_s3\\\/vendor\\\/aws\\\/aws-sdk-php\\\/src\\\/AwsClientTrait.php(58): GuzzleHttp\\\\Promise\\\\Promise->wait()\\n#11 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_primary_s3\\\/vendor\\\/aws\\\/aws-sdk-php\\\/src\\\/AwsClientTrait.php(77): Aws\\\\AwsClient->execute(Object(Aws\\\\Command))\\n#12 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_primary_s3\\\/lib\\\/s3storage.php(94): Aws\\\\AwsClient->__call('listBuckets', Array)\\n#13 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_primary_s3\\\/lib\\\/s3storage.php(143): OCA\\\\Files_Primary_S3\\\\S3Storage->init()\\n#14 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/ObjectStore\\\/ObjectStoreStorage.php(381): OCA\\\\Files_Primary_S3\\\\S3Storage->writeObject('urn:oid:34598', Resource id #125)\\n#15 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(349): OC\\\\Files\\\\ObjectStore\\\\ObjectStoreStorage->touch('files\\\/welcome.t...', 1527788721)\\n#16 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Availability.php(372): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->touch('files\\\/welcome.t...', NULL)\\n#17 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(349): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->touch('files\\\/welcome.t...', NULL)\\n#18 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(349): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->touch('files\\\/welcome.t...', NULL)\\n#19 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(349): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->touch('files\\\/welcome.t...', NULL)\\n#20 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(349): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->touch('files\\\/welcome.t...', NULL)\\n#21 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(1183): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->touch('files\\\/welcome.t...')\\n#22 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/View.php(565): OC\\\\Files\\\\View->basicOperation('touch', '\\\/dbuser\\\/files\\\/w...', Array, NULL)\\n#23 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Folder.php(177): OC\\\\Files\\\\View->touch('\\\/dbuser\\\/files\\\/w...')\\n#24 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/util.php(441): OC\\\\Files\\\\Node\\\\Folder->newFile('welcome.txt')\\n#25 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/util.php(412): OC_Util::copyr('\\\/var\\\/www\\\/ownclo...', Object(OC\\\\Files\\\\Node\\\\Folder))\\n#26 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(438): OC_Util::copySkeleton('dbuser', Object(OC\\\\Files\\\\Node\\\\Folder))\\n#27 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(513): OC\\\\User\\\\Session->prepareUserLogin(true)\\n#28 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/Events\\\/EventEmitterTrait.php(50): OC\\\\User\\\\Session->OC\\\\User\\\\{closure}(Array)\\n#29 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(525): OC\\\\User\\\\Session->emittingCall(Object(Closure), Array, 'user', 'login')\\n#30 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(324): OC\\\\User\\\\Session->loginWithPassword(*** sensitive parameters replaced ***)\\n#31 \\\/var\\\/www\\\/owncloud\\\/core\\\/Controller\\\/LoginController.php(201): OC\\\\User\\\\Session->login(*** sensitive parameters replaced ***)\\n#32 [internal function]: OC\\\\Core\\\\Controller\\\\LoginController->tryLogin(*** sensitive parameters replaced ***)\\n#33 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(159): call_user_func_array(Array, Array)\\n#34 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'tryLogin')\\n#35 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(103): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'tryLogin')\\n#36 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('LoginController', 'tryLogin', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#37 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#38 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(342): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#39 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(912): OC\\\\Route\\\\Router->match('\\\/login')\\n#40 \\\/var\\\/www\\\/owncloud\\\/index.php(55): OC::handleRequest()\\n#41 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/files_primary_s3\\\/vendor\\\/aws\\\/aws-sdk-php\\\/src\\\/WrappedHttpHandler.php\",\"Line\":191}"}
{"reqId":"Tv2vUJIZDclZYDiF9HcY","level":3,"time":"2018-05-31T17:45:22+00:00","remoteAddr":"172.18.0.7","user":"dbuser","app":"objectstore","method":"POST","url":"\/login","message":"Could not create object: No S3 ObjectStore available"}
{"reqId":"Tv2vUJIZDclZYDiF9HcY","level":3,"time":"2018-05-31T17:45:22+00:00","remoteAddr":"172.18.0.7","user":"dbuser","app":"index","method":"POST","url":"\/login","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Node.php(217): OC\\\\Files\\\\Node\\\\Node->getFileInfo()\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Node.php(117): OC\\\\Files\\\\Node\\\\Node->getPermissions()\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Node\\\/File.php(104): OC\\\\Files\\\\Node\\\\Node->checkPermissions(3)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/util.php(442): OC\\\\Files\\\\Node\\\\File->fopen('w')\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/util.php(412): OC_Util::copyr('\\\/var\\\/www\\\/ownclo...', Object(OC\\\\Files\\\\Node\\\\Folder))\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(438): OC_Util::copySkeleton('dbuser', Object(OC\\\\Files\\\\Node\\\\Folder))\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(513): OC\\\\User\\\\Session->prepareUserLogin(true)\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/Events\\\/EventEmitterTrait.php(50): OC\\\\User\\\\Session->OC\\\\User\\\\{closure}(Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(525): OC\\\\User\\\\Session->emittingCall(Object(Closure), Array, 'user', 'login')\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/User\\\/Session.php(324): OC\\\\User\\\\Session->loginWithPassword(*** sensitive parameters replaced ***)\\n#10 \\\/var\\\/www\\\/owncloud\\\/core\\\/Controller\\\/LoginController.php(201): OC\\\\User\\\\Session->login(*** sensitive parameters replaced ***)\\n#11 [internal function]: OC\\\\Core\\\\Controller\\\\LoginController->tryLogin(*** sensitive parameters replaced ***)\\n#12 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(159): call_user_func_array(Array, Array)\\n#13 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(89): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'tryLogin')\\n#14 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(103): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'tryLogin')\\n#15 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('LoginController', 'tryLogin', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#16 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#17 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(342): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#18 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(912): OC\\\\Route\\\\Router->match('\\\/login')\\n#19 \\\/var\\\/www\\\/owncloud\\\/index.php(55): OC::handleRequest()\\n#20 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Node.php\",\"Line\":97}"}
```

**Comment by ownclouders** [comment]
[GitMate.io](https://gitmate.io) thinks the contributors most likely able to help are @davitol, and @butonic.

**Comment by PVince81** [comment]
@DeepDiver1975 moving to backlog, unless you intend to work on this in the next sprint ?

**Comment by DeepDiver1975** [comment]
looks like the use logged in before the s3 app was fully configured -> close
